site_name: Arthur's AI Advisory Blog
site_url: https://arthurchan.github.io/my-blog
site_description: "A collection of essays and thoughts of Arthur"
site_author: Arthur Chan

theme:
  name: material
  logo: images/ArthurChanConsulting.ico
  palette:
    - scheme: default
      primary: blue
      accent: light blue
    - scheme: slate
      primary: blue
      accent: cyan
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.highlight

nav:
  - Home: index.md
  - About: about.md
  - Full bio: fullbio.md

extra_css:
  - assets/custom.css

markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.details

