site_name: Arthur's AI Advisory Blog
site_url: https://arthurchan.github.io/
site_description: "A collection of essays and thoughts of Arthur"
site_author: Arthur Chan

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
    - scheme: slate
      primary: blue
      accent: cyan
  font:
    text: Inter
    code: Fira Code
  logo: images/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.highlight

nav:
  - Home: index.md
  - Posts:
      - First Post: post1.md
      - Second Post: post2.md
  - About: about.md

extra_css:
  - assets/custom.css

markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.details

